### PR TITLE
Add additional AD40xx parts including support for dynamic sampling frequency

### PR DESCRIPTION
**Pull request by pdp7**
My goal for this PR is to allow @machschmitt and myself to sync up on the support for the AD40xx parts and the ADAQ4003.

This PR adds support for additional AD40xx parts and allows sampling frequency to be modified:
```
AD4000 AD4001 AD4002 AD4004 AD4005 AD4006 AD4008 AD4010 AD4021 AD4022
```

* Notes:
  * This is based somewhat on my original PR https://github.com/analogdevicesinc/linux/pull/2257 which attempted to add dynamic sampling frequency
  * I have rewritten the code in that PR to sit on top of the work @machschmitt has done for the ADAQ4003 as @machschmitt already added the dynamic sampling frequency infrastructure.
  * This PR is specifically based on testing/adaq4003 instead of dev/adaq4003 because the testing branch has newer commits
  * I don't consider this PR to in a merge-able state.  I feel I would need to break these changes into smaller commits.

* References:
  * GitHub issue: [Extend support for AD40xx with variable sample frequency #2239](https://github.com/analogdevicesinc/linux/issues/2239)
  *  Requires PWM peripheral in the updated BOOT.BIN (from @acostina in https://github.com/adi-ses/sea-misc/pull/27) that will be merged into the public HDL project

### CODE REVIEW

**Comment by machschmitt** [comment]
Hi @pdp7, thank you for your PR, I appreciate it.

Syncing our work is a good idea and it will be better for us when testing updates on the hdl project (we'll only need to look at one Linux branch, whatever branch we choose to work on).

I have included some patches from [adi-ad400x-sample-freq](https://github.com/pdp7/adi-linux/tree/adi-ad400x-sample-freq) here and because of that I see some merge conflicts now in this PR.
I resolved the merge conflicts on a [merge commit](https://github.com/machschmitt/linux/pull/1/commits/bebe662e49ef6fc36d44c0b690b754899f5a4695) but that might not be lead to the changes you wanted to add. Still, as this is marked as draft pull request I can't merge it (github doesn't enable the merge button).

If you want me to merge this, please undraft the PR.
If you want to rebase the changes and send another one I'll look at that too.

Thanks

**Comment by pdp7** [comment]
@machschmitt I've changed to a normal pull request, but you may want to just pick these 3 commits instead of actually merging [pdp7:machschmitt-testing-adaq4003_ad4020-debug](https://github.com/pdp7/adi-linux/tree/machschmitt-testing-adaq4003_ad4020-debug) into your branch _(sorry about the terribly long branch name)_
* 0b996bbf0dc7 dt-bindings: iio: adc: ad400x: Add additional parts
* a9b852cba60f iio: adc: ad400x: Add additional parts including max sampling freq
* 161b2025743a arch: arm: boot: dts: ad4020: Add pwm node to drive sampling frequency

**Comment by machschmitt** [comment]
Hello @pdp7, I picked the three commits you mentioned.
- 0b996bb dt-bindings: iio: adc: ad400x: Add additional parts
- 161b202 arch: arm: boot: dts: ad4020: Add pwm node to drive sampling frequency
- a9b852c iio: adc: ad400x: Add additional parts including max sampling freq

Note that `git cherry-pick` changes the commit hashes so they were introduced in this branch as 89e8aee8 and 605a29de5. a9b852c was already included with hash a74170e8.
Some commits had to be slightly adapted when applying.  I marked those by adding my sign-off below yours. Unchanged commits carry your sign-off only.

So, since this should work with AD4020 (ad400x) and ADAQ4003 I believe we can both work on top of these changes from now on. By the way, this is a good time to create a branch with a more suggestive name. One that might recall the fact that this is intended to support ad400x and adaq4003. I'm open to suggestions.

**Comment by pdp7** [comment]
> Note that `git cherry-pick` changes the commit hashes so they were introduced in this branch as [89e8aee](https://github.com/machschmitt/linux/commit/89e8aee8ccd4501d5955ff1cd5ccd421c46caa3e) and [605a29d](https://github.com/machschmitt/linux/commit/605a29de56b0f68207c2d8c3cbfe338bb2d6cd3c). [a9b852c](https://github.com/machschmitt/linux/commit/a9b852cba60f2dd85deccd292ba09445c12ac3b2) was already included with hash [a74170e](https://github.com/machschmitt/linux/commit/a74170e8dfc1eb7236b6e391b159d76ebf69ab3f). 

I don't think this is the case.   a9b852c ("iio: adc: ad400x: Add additional parts including max sampling freq") is quite different than [a74170e](https://github.com/machschmitt/linux/commit/a74170e8dfc1eb7236b6e391b159d76ebf69ab3f)("iio: adc: ad400x: Add additional supported parts").

The pull request I created on top of testing/adaq4003 was a fresh start from the work I had previously done.  It seems testing/adaq4003 now contains commits from my old adi master pull request https://github.com/analogdevicesinc/linux/pull/2257

This tree represents what I had thought the changes should look like: https://github.com/machschmitt/linux/commits/161b2025743ac64ee052eb0a1229a4a3b9476223

* https://github.com/machschmitt/linux/commit/a9b852cba60f2dd85deccd292ba09445c12ac3b2 made changes to ad400x.c
  * add more parts to `ad400x_ids`
  * introduce `struct ad400x_chip_info` with `chan_spec` and `max_rate`
  * add a pointer to a `ad400x_chip_info` in `struct ad400x_state`
  * relocate `AD400X_CHANNEL()` macro to be located before `ad400x_chips`
  * declare `ad400x_chips` which is an array of `struct ad400x_chip_info`, one for each part
  * change `ad400x_single_conversion()` to use `st->chip->max_rate` in `clamp()` instead of `ADAQ4003_MAX_FREQ`
  * remove `adaq4003_info` and add `.write_raw` to `ad400x_info` so that only one `struct iio_info` is need for all parts
  * change the `spi_device_id` array named `ad400x_id` to have a pointer to a `struct ad400x_chips` instead of an id from `enum ad400x_ids`
  * change `pwm_gen_setup()` to use `st->chip->max_rate` instead of `ADAQ4003_MAX_FREQ`
  * replace `enum ad400x_ids dev_id` with `struct ad400x_chip_info *chip` in `ad400x_probe()`
  * set `st->chip` so that this instance of `struct ad400x_state` points to the correct `struct ad400x_chip_info` for the part
  * always set `indio_dev->info` to `ad400x_info` as all parts support the same ops
  * always set `indio_dev->channels` to the `chan_spec` contained in the `struct ad400x_chip_info` for this part
  * set `st->samp_freq` to `st->chip->max_rate` instead of `1800000`
  * change the `of_device_id` array named `ad400x_of_match` to set `.data` to the `struct ad400x_chip_info` for a part in the `ad400x_chips` array
    * this was inspired by [Nuno's comment in my old PR](https://github.com/analogdevicesinc/linux/pull/2257#discussion_r1319874005)
    
* https://github.com/machschmitt/linux/commit/161b2025743ac64ee052eb0a1229a4a3b9476223 made changes to arch/arm/boot/dts/zynq-zed-adv7511-ad4020.dts
  * add adc_trigger and spi_clk nodes
  * change axi_spi_engine_0 clocks to `<&clkc 15 &spi_clk>`
  * change ad4020 compatible to `"adi,ad4020"`
  * add `<&spi_clk>` as `"ref_clk"`
  * add pwm channel `<&adc_trigger 0 0>` as `"cnv"`

**Pull request closed without merging**
